### ISSUE TITLE
Configurable doesn't exist

### ISSUE THREAD

**Issue by LimaJonas** [Magenmagic/DynamicSku#1]
I've been using version 1.0.0 released on marketplace.magento.com on localhost and it was working normally. However, when I put the website online it started to accuse this error

_Exception #0 (InvalidArgumentException): Plugin class Magenmagic\DynamicSku\Plugin\ConfigurableProduct\Block\Product\View\Type\Configurable doesn't exist_

If you can help me how to resolve this error. I'll be thankful.

I'm using Magento 2.3.6

**Comment by Magenmagic** [comment]
Hi Jonas

Could you give us access to the website?
The extension should work on your version of Magento, so we cannot say 
why this happened without investigating the problem on your website.
We suggest that the extension was installed incorrectly.

---
Best regards,
Anna Davis

**Comment by LimaJonas** [comment]
Unfortunately, I can't give you access. I will try to reinstall and resolve, if I can, I will answer
